version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: "/src/main/docker"
    schedule:
      interval: daily
